teleport-kube-agent:
  proxyAddr: "teleport.ronaldmiranda.com.br:443"
  kubeClusterName: ronald-cluster
  secretName: teleport-secret
  roles: kube,app
  kubernetesDiscovery:
  - types: ["app"]
    namespaces:
     - rnld
     - phpmyadmin
    labels:
      rnld-apps: teleport
  updater:
    enabled: false
