teleport-kube-agent:
  proxyAddr: "teleport.ronaldmiranda.com.br:443"
  kubeClusterName: ronald-cluster
  secretName: teleport-secret
  roles: kube,app,discovery
  appResources:
    - labels:
        teleport-enabled: app
  teleportConfig:
    discovery_service:
      poll_interval: 30s
  kubernetesDiscovery:
  - types: ["app"]
    namespaces:
     - rnld
     - rnld-logs
     - phpmyadmin
     - envoy-gateway-system
    labels:
      rnld-apps: teleport
  updater:
    enabled: false
